spring:
  profiles:
    active: dev

  application:
    name: taskboard-backend

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      "[hibernate.format_sql]": false

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
